name: JSON Validator
on: [push, pull_request]

jobs:
  validate-json:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install ajv-cli
        run: npm install -g ajv-cli

      - name: Validate textures.json
        run: ajv validate -s .github/schema/textures.json -d fonts/*/textures.json

      - name: Validate fonts.json
        run: ajv validate -s .github/schema/fonts.json -d fonts.json

      - name: Validate tileables.json
        run: ajv validate -s .github/schema/tileables.json -d tileables.json